### ISSUE TITLE
Segmentation fault due to `MSTPrim`

### ISSUE THREAD

**Issue by althonos** [refresh-bio/FAMSA#46] opened 2024-02-15 09:51 UTC
Hi Adam!

In althonos/pyfamsa#2 @davidlougheed reported some cases of segmentation fault, some of which I traced back to the original code. For instance the sequences `["BA", "BB", "BC"]` cause a segfault in both PyFAMSA and FAMSA.

I found an invalid write with `valgrind` that happens in the `MSTPrim` code: 

https://github.com/refresh-bio/FAMSA/blob/7eb7612c661362747709021e3a9ff2c2d89bbdca/src/tree/MSTPrim.cpp#L150-L157

Here, I found that with the test sequences above `pids.first` and `pids.second` might be `-1`, which causes an out-of-boundary write to the vector, and then causes a faulty deallocation. Not sure how to address the logic here but I think this should be covered.

**Comment by agudys** [comment] 2024-02-15 10:30
Hi Martin!

Thanks for reporting an issue -  I'll take a look on that.

Best,
Adam

**Comment by davidlougheed** [comment] 2024-02-15 12:49
thank you to you both!

**Comment by maovshao** [comment] 2024-04-27 10:56
Hello everyone, I am a user of PyFAMSA.

Is there any hope of solving this problem, or is there at least some way to avoid such errors?
@agudys @althonos 

I was actually running a large-scale pipeline, but the interruption caused by this problem made me very depressed.

Thank you all!

Best

**Comment by agudys** [comment] 2024-09-18 09:56
@davidlougheed @althonos @maovshao 
Hello! The issue has been fixed in the latest (2.2.3) release.

**Closed by agudys** 2024-09-18 09:56 UTC
Labels: bug
